CREATE DATABASE `bullet` /*!40100 COLLATE 'utf8_general_ci' */;
CREATE USER 'bullet'@'localhost' IDENTIFIED BY 'bullet';
GRANT USAGE ON *.* TO 'bullet'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `bullet`.* TO 'bullet'@'localhost' WITH GRANT OPTION;
